# Copyright (c) 2013-2016 Software Architecture Group (Hasso Plattner Institute)
# Copyright (c) 2015 Fabio Niephaus, Google Inc.

language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6
